export const TodosActions = {
  BEFORE_LOAD_TODOS: 'BEFORE_LOAD_TODOS',
  AFTER_LOAD_TODOS_SUCCESS: 'AFTER_LOAD_TODOS_SUCCESS',
  AFTER_LOADO_TODOS_ERROR: 'AFTER_LOADO_TODOS_ERROR',

  BEFORE_CREATE_TODO: 'BEFORE_CREATE_TODO',
  AFTER_CREATE_TODO_SUCCESS: 'AFTER_CREATE_TODO_SUCCESS',
  AFTER_CREATE_TODO_ERROR: 'AFTER_CREATE_TODO_ERROR',

  BEFORE_UPDATE_TODO: 'BEFORE_UPDATE_TODO',
  AFTER_UPDATE_TODO_SUCCESS: 'AFTER_UPDATE_TODO_SUCCESS',
  AFTER_UPDATE_TODO_ERROR: 'AFTER_UPDATE_TODO_ERROR',

  BEFORE_REPLACE_TODO: 'BEFORE_REPLACE_TODO',
  AFTER_REPLACE_TODO_SUCCESS: 'AFTER_REPLACE_TODO_SUCCESS',
  AFTER_REPLACE_TODO_ERROR: 'AFTER_REPLACE_TODO_ERROR',

  BEFORE_DELETE_TODO: 'BEFORE_DELETE_TODO',
  AFTER_DELETE_TODO_SUCCESS: 'AFTER_DELETE_TODO_SUCCESS',
  AFTER_DELETE_TODO_ERROR: 'AFTER_DELETE_TODO_ERROR',
};

export const TodosFormActions = {
  SET_TODO: 'SET_TODO',
};
